name: '532'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel>=6.0.0
    - altair-all>=5.0.0
    - dash>=2.16.0
    - dash-bootstrap-components>=1.5.0
    - plotly>=5.0.0
    - pytest
    - pip
    - pip:
        - dash-vega-components
        - Flask-Caching==2.1.0
