# Install the conda environment with the following command:
# conda env create -f environment.yaml
# Once you install it, you should be able to see it in your Jupyter Lab.
# If not, check the documentation here: https://ipython.readthedocs.io/en/stable/install/kernel_install.html
name: '532'
channels:
    - conda-forge
    - defaults
dependencies:
    - altair=5.1.2
    - ipykernel=6.26.0
    - pandas=2.1.2
    - python=3.11.6
    - notebook=6.5.4
    - jupyter_contrib_nbextensions=0.7.0
    - nb_conda_kernels=2.5.1
    - jupyterlab=4.3.1
    - matplotlib=3.9.2
    - dash=2.16.0
    - dash-bootstrap-components=1.5.0
    - plotly=5.0.0
    - vegafusion=1.6.9
    - vegafusion-python-embed=1.6.9
    - pip
    - pip:
        - dash-vega-components
        - Flask-Caching==2.1.0
        - dash-leaflet
        - dash-loading-spinners==1.0.0
